import java.util.ArrayList;

/**
 * CS 180 - Project 5
 *
 * This is the Drone Class
 *
 * @author Nick Huber, Jon Bradbury, Gabe Efsits
 * @version 12/9/18
 */

public class Drone extends Vehicle {

    final private double gasRate = 1.33;
    private String licensePlate;
    private double maxWeight;

    /**
     * Default Contructor 
     */
    //============================================================================
    public Drone() {
        super();
    } // end Drone

    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Drone(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    } // end Drone

    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */
    /**
     * Returns the profits generated by the packages currently in the Truck.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.33)
     * </p>
     */
    @Override
    public double getProfit() {
        Vehicle vehicle = new Vehicle();
        Package packages = new Package();

        return packages.getPrice() - (vehicle.getRange() * this.gasRate);
    } // end getProfit

    /**
     * Generates a String of the Drone report. Drone report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     *
     * @return Truck Report
     */
    @Override
    public String report() {
        Vehicle vehicle = new Vehicle();
        String shippingLabels = "";

        for (int i = 0; i < vehicle.getPackages().size(); i++) {
            shippingLabels += this.getPackages().get(i).shippingLabel();
        } // end for

        return "==========Truck Report==========\n" +
                "License Plate No.: " + this.licensePlate +
                "Destination: " + vehicle.getZipDest() +
                "Weight Load: " + vehicle.getCurrentWeight() + "/" + this.maxWeight +
                "Net Profit: $" + getProfit() +
                "=====Shipping Labels=====\n" +
                shippingLabels + "\n" +
                "==============================";
    }

    public String getType() {
        return "Drone";
    }

}