import java.util.ArrayList;


/**
 * <h1>Truck</h1> Represents a Truck
 */
public class Truck extends Vehicle {

    private final double GAS_RATE = 1.66;
    private String licensePlate;
    private double maxWeight;

    /**
     * Default Constructor
     */
    //============================================================================
    public Truck() {
        super();
    }

    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Truck(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }

    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */
    /**
     * Returns the profits generated by the packages currently in the Vehicle.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.66)
     * </p>
     */
    @Override
    public double getProfit() {
        Package packages = new Package();
        Vehicle vehicle = new Vehicle();

        return packages.getPrice() - (vehicle.getRange() * this.GAS_RATE);
    }

    /**
     * Generates a String of the truck report. Truck report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     *
     * @return Truck Report
     */
    @Override
    public String report() {
        Vehicle vehicle = new Vehicle();
        String shippingLabels = "";

        for (int i = 0; i < vehicle.getPackages().size(); i++) {
            shippingLabels += this.getPackages().get(i).shippingLabel();
        } // end for

        return "==========Truck Report==========\n" +
                "License Plate No.: " + this.licensePlate +
                "Destination: " + vehicle.getZipDest() +
                "Weight Load: " + vehicle.getCurrentWeight() + "/" + this.maxWeight +
                "Net Profit: $" + getProfit() +
                "=====Shipping Labels=====\n" +
                shippingLabels + "\n" +
                "==============================";
    }

    public String getType(){
        return "Truck";
    }


}